---
- name: install initial packages on all boxes
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: install all initial packages
    yum:
      name: "{{ item }}"
      state: latest
      with_items:
      - man
      - man-pages
      - mlocate
      - bind-utils
      - ftp

  tasks:
  - name: install ntp packages
    yum:
      name: ntp
      state: latest
  - name: configure ntp
    template:
      src: /ansible/templates/ntp.conf.j2
      dest: /etc/ntp.conf
    notify: restart ntpd
  - name: start ntpd
    service:
      name: ntpd
      state: started
  handlers:
    - name: restart ntpd
      service:
        name: ntpd
        state: restarted

  tasks:
  - name: manage resolv.conf
    template:
      src: /ansible/templates/resolv.conf.j2
      dest: /etc/resolv.conf
  - name: remove Network Manager
    yum:
      name: NetworkManager
      state: absent
      
   tasks:
  - name: install httpd packages
    yum:
      name: httpd
      state: latest
  - name: configure httpd
    template:
      src: /ansible/templates/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: restart httpd
  - name: start httpd
    service:
      name: httpd
      state: started
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
