---
  - name: install initial packages on all boxes
    hosts: webservers
    remote_user: ansible
    become: yes

    tasks:
  - name: install all initial packages
    yum:
      name: {{item}}
      state: latest
      with_items:
      - man
      - man-pages
      - mlocate
      - bind-utils
  - name: install ntp packages
    yum:
      name: ntp
      state: latest
  - name: configure ntp
    template:
      src: /ansible/templates/ntpd.conf.j2
      dest: /etc/ntp.conf
    notify: restart ntpd
  - name: start ntp
    service:
      name: ntpd
      state: started
    handlers:
  - name: restart ntpd
      service:
      name: ntpd
      state: restarted
  tasks:
  - name:
     template:
      src: /ansible/playbooks/templates/resolv.conf.j2
      dest: /etc/resolv.conf
  - name: stop Network Manager
    service:
      name: NetworkManager
      state: stoped
      enabled: no
