---
-
  name: install initial packages on all boxes
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
  -name: install all initial packages
    yum:
      name: "{{ item }}"
      state: latest
      with_items:
      - postfix
      - telnet
      - mailx
