---
-
  name: install initial packages on all boxes
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: install all initial packages
    yum:
      name: "{{ item }}"
      state: latest
      with_items:
      - man
      - man-pages
      - mlocate
      - bind-utils
      - ftp
      - sysstat
      - epel-release
      - postfix
      - ntp
      - autofs
      - nfs-utils
      - openldap-clients
      - nss-pam-ldapd
