---
-
  name: install initial packages on all boxes
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo

  tasks:
  - name: install all initial packages
    yum:
      name:
      - man
      - man-pages
      - mlocate
      - bind-utils
      - ftp
      - sysstat
      - epel-release
      - postfix
      - ntp
      - autofs
      - nfs-utils
      - openldap-clients
      - nss-pam-ldapd
      state: latest
  - name: stop firewall
    state: stopped
    enabled: no
  - name: enable selinux
    command: /sbin/setenforce 0
